---
title: "Homework5"
author: "Sam Troast"
date: "2025-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Question 1**
```{r}
# Assign to the variable n_dims a single random integer between 3 and 10.
n_dims <- sample(3:10,1)
print(n_dims)

# Create a vector of consecutive integers from 1 to n_dims^2.
my_vec <- 1:n_dims^2

# Use the sample function to randomly reshuffle these values.
my_vec <- sample(my_vec)
print(my_vec)

# Create a square matrix with these elements
my_square <- matrix(data=(my_vec^2),nrow= n_dims, ncol=n_dims)
# and print matrix
print(my_square)

# Find a function in R to transpose the matrix
my_matrix <- t(my_square)
# print it out again and not how it has changed
print(my_matrix)
# It work, it transposed the matrix!

# Calculate the sum and the means of the elements in the first row and then the last row
my_sum_f <- sum(my_matrix[1,])
print(my_sum_f)
my_mean_f <- mean(my_matrix[1,])
print(my_mean_f)
my_sum_l <- sum(my_matrix[length(n_dims),])
print(my_sum_l)
my_mean_l <- mean(my_matrix[length(n_dims),])
print(my_mean_l)

# Read about the eigen() function and use it on your matrix 
eigen_matrix <- eigen(my_matrix)
print(eigen_matrix)

# Look carefully at the elements of $values and $vectors in the output. What kind of numbers are these?
typeof(eigen_matrix)
# They are decimal(imaginary) numbers. It's a list!

# If the code is set up properly, you should be able to re-run it and create a matrix of different sizes because n_dims will change. 

```
**Question 2**
```{r}
# Create a list with the following named elements:

# my_matrix, which is a 4 x 4 matrix filled with random uniform values
my_matrix <- matrix(data=runif(4),nrow=4, ncol=4)
print(my_matrix)

# my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
my_logical <- runif(100) < 0.5
print(my_logical)

# my_letters, which is a 26-element vector of all the lower-case letters in random order.
my_letters <- sample(letters, 26)
print(my_letters)

# Then, complete the following steps

# Create a new list, which has the element [2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector
group_list <- list(my_matrix[2,2], my_logical[2],my_letters[2])
print(group_list)

# use the typeof() function to confirm the underlying data types of each component in this list.
typeof(my_matrix)
typeof(my_logical)
typeof(my_letters)

# combine the underlying elements from the new list into a single atomic with the c() function
group_con <- c(my_matrix[2,2], my_logical[2],my_letters[2])
print(group_con)

# What is the data type of this vector?
typeof(group_con)
# It's character!
```
**Question 3**
```{r}
# Create a data frame with the two variables (=columns) and 26 cases (=rows) below:
my_unis_10<- sample(0:10)
my_unis_20<- sample(0:10)
my_unis_26<- sample(0:10, 4)
my_unis <- c(my_unis_10,my_unis_20,my_unis_26)
print(my_unis)

# Call the second variable my_letters and fill it with capital letters in random order.
my_letters <- sample(LETTERS, 26)
print(my_letters)

df <- data.frame(my_unis,my_letters)
print(df)

# For the first variable, use a single line of code to select 4 random rows and replace the numerical values in those rows with NA
df$my_unis[sample(0:nrow(df), 4)] <- NA
print(df)

# For the first variable, write a single line to identify which rows have the missing values. 
which(!complete.cases(df$my_unis))

# re-order the entire data frame to arrange the second variable in alphabetical order
df_letters <- df[order(df$my_letters),]
print(df_letters)

# calculate the column mean for the first variable 
unis_means <- mean(df$my_unis, na.rm = TRUE)
print(unis_means)

```
